apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-dev
  labels:
    app: my-react-app-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react-app-dev
  template:
    metadata:
      labels:
        app: my-react-app-dev
    spec:
      containers:
      - name: my-react-app-dev
        image: myregistry.io/my-docker-repo/my-react-app-dev:latest
        ports:
        - containerPort: 80
